services:
  app:
    build: .
    ports:
      - 3333:3333
    volumes:
      - .:/home/node/app
    depends_on:
      - db

  db:
    image: postgres:latest
    ports:
      - "${DB_PORT}:5432"
    environment:
      POSTGRES_DB: ${DB_DATABASE}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}