services:
  app:
    build: .
    ports:
      - 3333:3333
    volumes:
      - .:/home/node/app
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres:latest
    ports:
      - "${DB_POSTGRES_PORT}:5432"
    environment:
      POSTGRES_DB: ${DB_POSTGRES_DATABASE}
      POSTGRES_USER: ${DB_POSTGRES_USER}
      POSTGRES_PASSWORD: ${DB_POSTGRES_PASSWORD}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_POSTGRES_USER} -d ${DB_POSTGRES_DATABASE}"]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s